// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3nGXFS68cvt7RpHSf0EFec8-knj7mms',
    appId: '1:220842399603:web:e29381002cd96f9b0c5706',
    messagingSenderId: '220842399603',
    projectId: 'netflix-clone-ffeab',
    authDomain: 'netflix-clone-ffeab.firebaseapp.com',
    storageBucket: 'netflix-clone-ffeab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOh6y3GAJ9JIVAE1hvXbT3SRJvPO2-IHw',
    appId: '1:220842399603:android:56e3070c7fee623b0c5706',
    messagingSenderId: '220842399603',
    projectId: 'netflix-clone-ffeab',
    storageBucket: 'netflix-clone-ffeab.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt3nGXFS68cvt7RpHSf0EFec8-knj7mms',
    appId: '1:220842399603:web:d3404277b56d41fb0c5706',
    messagingSenderId: '220842399603',
    projectId: 'netflix-clone-ffeab',
    authDomain: 'netflix-clone-ffeab.firebaseapp.com',
    storageBucket: 'netflix-clone-ffeab.appspot.com',
  );

}